map_merge:
  ros__parameters:
    known_init_poses: true  
    merging_rate: 1.0
    discovery_timeout: 5.0
    estimation_rate: 0.5
    estimation_confidence: 0.1
    world_frame: map  # Frame globale pour la fusion (IMPORTANT!)
    
# Positions initiales dans le namespace de chaque robot
TB3_1:
  map_merge:
    ros__parameters:
      init_pose_x: -2.0
      init_pose_y: -0.5
      init_pose_z: 0.0
      init_pose_yaw: 0.0

TB3_2:
  map_merge:
    ros__parameters:
      init_pose_x: 0.5
      init_pose_y: -2.0
      init_pose_z: 0.0
      init_pose_yaw: 0.0
